version: '3.8'

services:
  tenant-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
        - multi-tenancy
networks:
  multi-tenancy:
    external: true
